FROM eclipse-temurin:25-jdk
WORKDIR /app

ARG JAR_FILE=build/libs/*.jar
ARG CONFIGS_ROOMS=configs/rooms.json
ARG CONFIGS_SCHEDULES=configs/schedules.json

COPY ${JAR_FILE} app.jar
COPY ${CONFIGS_ROOMS} configs/rooms.json
COPY ${CONFIGS_SCHEDULES} configs/schedules.json

ARG INTERNAL_REPO_LOGIN
ARG INTERNAL_REPO_PASSWORD
ENV INTERNAL_REPO_LOGIN=$INTERNAL_REPO_LOGIN
ENV INTERNAL_REPO_PASSWORD=$INTERNAL_REPO_PASSWORD

#RUN chmod +x gradlew && ./gradlew assemble
EXPOSE 8080
CMD ["java", "-Dspring.profiles.active=docker", "-jar", "/app/app.jar"]
