spring:
  datasource:
    url: jdbc:postgresql://82.202.138.26:5430/hostelService

schedules:
  timeslots:
    path: /app/configs/schedules.json
  kitchen:
    path: /app/configs/rooms.json

rabbitmq:
  timeslots:
    addresses: 82.202.138.26:5672

otlp:
  tracing:
    endpoint: http://tempo.monitoring.svc.cluster.local:4317