spring:
  datasource:
    url: jdbc:postgresql://82.202.138.26:5430/hostelService

schedules:
  timeslots:
    path: /app/configs/schedules.json
  kitchen:
    path: /app/configs/rooms.json

rabbitmq:
  timeslots:
    addresses: 82.202.138.26:5672
  notification-service:
    addresses: 82.202.138.26:5672

otlp:
  tracing:
    endpoint: http://tempo.monitoring.svc.cluster.local:4317

# На будущее
#server:
#  port: 8443
#  http2:
#    enabled: true
#  ssl:
#    enabled: true
#    key-store: file:/etc/nginx/keystore2.p12y
#    key-password: TpaBKa
#    key-store-type: PKCS12