spring:
  datasource:
    url: jdbc:postgresql://82.202.138.26:5430/hostelService

schedules:
  timeslots:
    path: /app/src/main/java/ru/tpu/hostel/schedules/schedules/schedules.json
  kitchen:
    path: /app/rooms.json

rabbitmq:
  schedules-service:
    addresses: 82.202.138.26:5672