name: Check Tasks in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check tasks in comments
        run: |
          # Получаем комментарии PR через GitHub API
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments")

          # Проверяем, есть ли незавершённые задачи (ищем "- [ ]" в комментариях)
          if echo "$COMMENTS" | grep -q '\- \[ \]'; then
            echo "Есть незавершённые задачи!"
            exit 1
          else
            echo "Все задачи выполнены."
          fi
